on: [push, pull_request]

jobs:
  uboot:
    # The host should always be Linux
    runs-on: ubuntu-latest
    name: Build U-Boot
    steps:
      - uses: actions/checkout@v2.1.0
        name: checkout src
        id: checkout
      - name: Compile U-Boot
        id: compile
        run: |
            bash build.sh

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.UBOOT_VER }}
          name: "U-Boot ${{ env.UBOOT_VER }} for beikeyun"
          draft: true
          files: |
            uboot-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

